name: workflow1
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        
        steps:
        - name: Output event data
          run: echo "${{toJson(github.event)}}"
        - name: Output event data
          uses: actions/checkout@v3
        - name: install dependencies
          run: npm ci
        - name: lint
          run: npm run lint
        - name: test
          run: npm run test
        - name: build
          run: npm run build
        - name: deploy
          run: echo "Deploying . . . "
    
        